#' Download/process ECCC HRDPA rasters
#'
#' @description
#' `r lifecycle::badge("stable")`
#' 
#' NOTE: If you have access to the WRB aquacache these rasters are already in there. Use function [getRaster()] to extract what you need to a .tiff file.
#'
#' Utility function to retrieve and minimally process precipitation reanalysis rasters generated by the Canadian Precipitation Analysis (CaPA) System [HRDPA](https://eccc-msc.github.io/open-data/msc-data/nwp_hrdpa/readme_hrdpa_en/), clips them to a designated province/region, and saves them to a designated location in .tiff format.
#'
#' CaPA outputs precipitation estimates valid at  00, 06, 12 and 18 UTC for the 6-hour rasters. The start and end times you specify will be automatically adjusted to the nearest or most recent match. Note that there is a 1-hour delay in the issuing of CaPA outputs. In addition, a preliminary version of the output is issued ~one hour post with a final version output ~7 hours post incorporating observation data for model corrections. This function will look for 1-hour post rasters in the save path and replace them with 7-hour post files whenever possible.
#'
#' Start and end times are automatically converted to UTC if supplied as class "character"; input times/dates of class POSIXct if you wish to specify a time zone.
#'
#' Be aware that your requested time period may not be realized when requesting an end time close to the current time. This will occur if ECCC experiences an unusual delay in the issuance of the 1-hour raster. These are normally issued prior to 1 hour and 10 minutes of the valid time, issues may arise is they are delayed by more than 1 hour and 12 minutes.

#' @param start The start of the time period for which you want HRDPA rasters, up to one month prior to today. Use format `"yyyy-mm-dd hh:mm"` (character vector) in local time. See details for more info.
#' @param end The end of the time period for which you want HRDPA rasters. Other details as per `start`.
#' @param clip The two-digit abbreviation(s) as per [Canadian Census](https://www12.statcan.gc.ca/census-recensement/2021/ref/dict/tab/index-eng.cfm?ID=t1_8) for the province(s) with which to clip the HRDPA. A 300 km buffer is added beyond the provincial boundaries. Set to NULL for no clip.
#' @param save_path The path to the directory (folder) where the raster(s) should be saved. Default 'choose' lets you select your folder, or enter the path as a character string. Any necessary rasters already in the save path will not be downloaded again. You must specify a save path when running in non-interactive mode.
#'
#' @return One of more rasters of precipitation amounts over 6 hour periods saved where specified. The date/time stamp in the file name refers to the end of the 6-hour valid period. Output is not assigned to an object, load the raster from the save_path if desired.
#'
#' @seealso [getHRDPS()] if looking for forecast precipitation and other parameters in .tif format. For nice precipitation maps and tabular reports of precipitation (past or future), try [basinPrecip()].
#' @export
#'
getHRDPA <- function(start = Sys.time() - 60*60*24,
                     end = Sys.time(),
                     clip = c("YT"),
                     save_path = "choose")
{
  # Save path
  if (save_path == "choose") {
    if (!interactive()) {
      stop("You must specify a save path when running in non-interactive mode.")
    }
    message("Select the path to the folder where you want this report saved.")
    save_path <- rstudioapi::selectDirectory(caption = "Select Save Folder")
  }

  # Determine the sequence of files within the start:end window, compare against what exists in save_path, make list of files to dl. #####
  start <- as.POSIXct(start) + 60*60*4.8 #Assuming that rasters are issued a bit more than one hour post valid time, this sets the start time so that the 6 hours before the requested start time is not included.
  end <- as.POSIXct(end)
  attr(start, "tzone") <- "UTC"
  attr(end, "tzone") <- "UTC"
  start <- lubridate::floor_date(start, "6 hours")
  end <- lubridate::floor_date(end, "6 hours")

  available <- data.frame()
  for (i in c("00", "06", "12", "18")){
    tmp <- xml2::read_html(paste0("https://dd.weather.gc.ca/model_hrdpa/2.5km/", i, "/"))
    tmp <- rvest::html_elements(tmp, xpath='//*[contains(@href, ".grib2")]') %>%
      rvest::html_attr("href")
    available <- rbind(available, as.data.frame(as.character(tmp)))
  }

  names(available) <- "link"
  available$cutoff <- "0700"
  available$cutoff[grepl("Prelim", available$link)] <- "0100"
  available$valid <- NA
  available$valid <- as.POSIXct(substr(available$link, 1, 11), format = "%Y%m%dT%H", tz="UTC")
  available$integrate_time <- "6h"
  available$integrate_time[grepl("Accum24h", available$link)] <- "24h"

  last_available_01 <- available[available$valid == max(available$valid) & available$cutoff == "0100" & available$integrate_time == "6h", "valid"]
  last_available_07 <- available[available$valid == max(available$valid) & available$cutoff == "0700" & available$integrate_time == "6h", "valid"]
  first_available_01 <- available[available$valid == min(available$valid) & available$cutoff == "0100" & available$integrate_time == "6h", "valid"]
  first_available_07 <- available[available$valid == min(available$valid) & available$cutoff == "0700" & available$integrate_time == "6h", "valid"]

  #Make to nearest available time (correct times if they specify a yet-to-exist or no longer present file)
  if (start > last_available_01){
    start <- last_available_01
  }
  if (end > last_available_01){
    end <- last_available_01
  }
  if (start < first_available_07){
    start <- first_available_07
  }
  if (end < first_available_07){
    end <- first_available_07
  }
  #now make the sequence
  sequence <- as.character(seq.POSIXt(start, end, by= "6 hour"))
  #Add trailing hour:minutes for the midnights
  for (i in 1:length(sequence)){
    if(nchar(sequence[i]) < 13){
      sequence[i] <- paste0(sequence[i], " 00")
    }
  }

  #Make clip polygon
  extent <- paste(clip, collapse="_")
  if (!is.null(clip)){
    clip <- prov_buff[prov_buff$PREABBR %in% clip, ]
    if (nrow(clip) == 0){
      clip <- NULL
    }
  }

  #Download the HRDPAs within the time window, save to disc. Don't re-dl files except to replace 1-hour-post raster with 7-hour-post
  clipped <- FALSE #So that clip gets projected the first time around
  for (i in sequence){
    name <- paste0(ifelse(is.null(clip)==FALSE, paste0("clipped_", extent, "_"), ""), "HRDPA_6hrs_07_", substr(i, 1, 13), ".tiff")
    name <- gsub(" ", "", name)
    name <- gsub("-", "", name)

    #Only download if raster doesn't already exist
    if (!(name %in% list.files(save_path))){
        if (httr::HEAD(paste0("https://dd.weather.gc.ca/model_hrdpa/2.5km/", substr(i, 12, 13), "/", substr(i, 1,4), substr(i, 6,7), substr(i, 9,10), "T", substr(i, 12,13), "Z_MSC_HRDPA_APCP-Accum6h_Sfc_RLatLon0.0225_PT0H.grib2"))$status_code == 200){ #First try downloading the 7-hour post files
      raster <- terra::rast(paste0("https://dd.weather.gc.ca/model_hrdpa/2.5km/", substr(i, 12, 13), "/", substr(i, 1,4), substr(i, 6,7), substr(i, 9,10), "T", substr(i, 12,13), "Z_MSC_HRDPA_APCP-Accum6h_Sfc_RLatLon0.0225_PT0H.grib2"))
      } else { #...but if one is missing because data requested is too recent, get the 1-hour file
        name <- sub("07", "01", name)
        if (!(name %in% list.files(save_path))){ #But don't re-download it if it already exists!
          raster <- terra::rast(paste0("https://dd.weather.gc.ca/model_hrdpa/2.5km/", substr(i, 12, 13), "/", substr(i, 1,4), substr(i, 6,7), substr(i, 9,10), "T", substr(i, 12,13), "Z_MSC_HRDPA-Prelim_APCP-Accum6h_Sfc_RLatLon0.0225_PT0H.grib2"))
        }
      }

      if (exists("raster")){
        raster <- raster[[1]]
        if (clipped == FALSE){
          if (!is.null(clip)){
            clip <- terra::project(clip, raster) #project clip vector to crs of the raster
          }
          clipped <- TRUE #So that project doesn't happen after the first iteration
        }

        if (!is.null(clip)){
          raster <- terra::mask(raster, clip) #Makes NA values beyond the boundary of clip
          raster <- terra::trim(raster) #Trims the NA values
        }

        terra::writeRaster(raster, paste0(save_path, "\\", name), overwrite=TRUE)
        rm(raster)
        unlink(paste0(tempdir(), "/HRDPA", i))
      }
    }
  } #End of DL sequence

  #Clean up old 1-hour files if they are supplanted by 7-hours
  old.files <- list.files(save_path, pattern = "_01")
  if (length(old.files > 0)){
    for (i in old.files){
      #Check if a 7-hour file with same date/time exists, delete if TRUE
      match.name <- sub(01,07,i)
      if (file.exists(paste0(save_path, "/", match.name))){
        file.remove(paste0(save_path, "/", i))
      }
    }
  } #End of clean-up

} #End of function
